- src/core/sock/sockinfo_tcp.cpp
Segmentation fault in tcp timers, where we delete sockinfo_tcp object, and then call unlock for that object.
The fix - first unlock and only then delete the object.
> issue: 3574901 Unlock sockinfo_tcp before destruction

- src/core/dev/cq_mgr.cpp
- src/core/dev/cq_mgr.h
- src/core/dev/cq_mgr_mlx5.cpp
- src/core/dev/cq_mgr_mlx5.h
- src/core/dev/cq_mgr_mlx5_strq.cpp
- src/core/dev/cq_mgr_mlx5_strq.h
- src/core/dev/qp_mgr.cpp
- src/core/dev/ring_simple.cpp
1. Remove special socketxtreme drain and poll_and_process methods for non socketxtreme_poll flows. 
- This fixes GRO flush segfaults and allows single flow for any polling method
2. Improve GRO flush during socketxtrme_poll. 
- Allow flushed events to be collected on the same call up to a limit of ncompletions.
With this PR also following issues were not seen:
https://redmine.mellanox.com/issues/3568465
https://redmine.mellanox.com/issues/3568428
Low-scale performance crypto:
|                  |  3.20.1 |  LRO   | LRO+GRO+flags |
| ----------- | ------- | ------- | ------------------ |
| randread  |   2177  |   2199 |  2212                  |
| randwrite |   1999  |   2006 |                            |
| randrw     |  1780   |  1798  | 1840                   |
High-scale performance …
> issue: 3531436 Fixing GRO polling and flush segfault

- contrib/build_pkg.sh
Update default repo url for build_pkg.sh
Change default url to https://github.com/Mellanox/libxlio
Fix clone issue.
> issue: 3480683 Update default repo url for build_pkg.sh

- contrib/jenkins_tests/test.sh
CI Test phase slowness
CI Test phase sets 20000 RX buffers which require too much memory in case of striding RQ.
CI failures
Remove buffers setting from the test
> Fix dpcp CI Test buffers

- src/core/lwip/tcp_in.c
TCP stream corruption
Equality checks in lwip on seqno related parameters must be done using special macros to a handle situations when seqno wraps around.
TCP stream corruption in case of OOO packets
> issue: 3591210 Fixing lwip seqno wrap around condition

- src/core/dev/ib_ctx_handler.cpp
- src/core/util/utils.cpp
- src/core/util/utils.h
Deleted check for locked memory during initialization of XLIO and added a message to the user when the locked memory is not enough.
Notifies the user to check locked memory in kernel, and provides a possible problem and solution user should check
> issue: 3427021 Removed generic warning that was prompted each time XLIO ran

- config/m4/compiler.m4
- config/m4/utls.m4
- src/core/Makefile.am
- src/core/dev/cq_mgr.h
- src/core/dev/cq_mgr_mlx5.h
- src/core/dev/qp_mgr_eth_mlx5.h
- src/core/dev/ring_simple.h
- src/core/proto/dst_entry.cpp
- src/core/proto/dst_entry.h
- src/core/sock/pipeinfo.cpp
- src/core/sock/pipeinfo.h
- src/core/sock/sock-redirect-internal.h
- src/core/sock/sock-redirect.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_ulp.cpp
- src/core/sock/sockinfo_ulp.h
- tools/daemon/tc.c
There are multiple issues with clang:
- UTLS detection always fails because clang doesn't build the autotools code snippet
- UTLS related code doesn't have consistent override keyword
- xliod fails to compile because of a GNU extension
- clang fails to compile XLIO syscall implementation when the fortified version exists
Fix compilation errors with clang-16.
Compilation issues.
> issue: 3592264 Fix compilation with modern clang

- src/core/proto/header.cpp
- src/core/proto/header.h
Segfault during IPv6 send packets
IPv6 header copy constructor does not set m_actual_hdr_addr.
The issue popped out after latest changes.
Fix crash
> issue: 3601148 Fixing IPv6 header copy

- src/core/dev/qp_mgr.cpp
- src/core/dev/qp_mgr.h
- src/core/dev/qp_mgr_eth_mlx5.h
When the ring is destroyed and the RQ is empty the termination loop becomes infinte. It waits for the last_posted_wqe to be retrieved. but since it is empty the last posted wqe was already retrieved.
XLIO stuck infinitely in ring destruction
If the RQ is empty, ring destruction will loop inifintely.
See more details in commit message
Fixing stuck XLIO
Try to fetch last posted wqe only if the RQ is not empty.
> issue: 3286324 Fixing stuck empty rx ring cleanup

- README
- src/core/main.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
This is a part of hugepage optimization effort. PR is rebased on top of #22, only 2 commits are relevant.
Introduce option_size namespace with from_str() and to_str() methods to simplify and unify parameters which represent size. This approach follows other option-like implementations.
option_size::from_str() accepts dec, hex, oct formats and case insensitive suffixes B, K/KB, M/MB, G/GB. This is more convenient for big numbers.
Introduce option_size namespace with from_str() and to_str() methods.
Simplify and unify parameters which represent size. Out of box user experience improvement.
> issue: 3580073 Add option_size for size parameters

- src/core/dev/qp_mgr_eth_mlx5.h
is_empty_rq method was put under DEFINED_UTLS
Moving is_empty_rq 
is_empty_rq should be always available
> issue: 3286324 Moving is_empty_rq to outside of UTLS ifdef

- src/core/proto/neighbour.cpp
Recover neigh after ling down/up.
After link down state neigh entry is destroyed.
On connect() call during link down neigh can not complete initialization and move from state ST_ERROR
to state ST_NOT_ACTIVE with next state SM_ST_STAY(-3).
Time for moving to this state is controlled by XLIO_NEIGH_NUM_ERR_RETRIES.
When link is up neigh can be reachable and event EV_ARP_RESOLVED signals about this.
So this change allows to move from ST_NOT_ACTIVE to EV_ARP_RESOLVED skipping ST_INIT, ST_INIT_RESOLUTION, ST_SOLICIT_SEND.
Fix issue related link down/up case.
RM#3602243 
> issue: 3602243 Recover neigh after link down/up

- src/core/dev/buffer_pool.cpp
- src/core/dev/buffer_pool.h
- src/core/main.cpp
- src/core/sock/tcp_seg_pool.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
**Note, only 2 last commits are relevant.**
Print a report during XLIO termination on buffer allocation errors. Undocumented parameter XLIO_PRINT_REPORT controls this feature and is disabled by default.
Print report at exit on buffer errors.
Improve observability of runtime resource allocation failures.
> issue: 3580084 Print report at exit on buffer errors

- src/core/dev/src_addr_selector.cpp
In case of empty list of IP addresses in src selection, we should not access the vector to prevent seg fault.
Return nullptr instead.
> issue: 3600396 Handle empty IP list in ipv4_select_saddr

- contrib/jenkins_tests/gtest.sh
- src/core/event/event_handler_manager.h
- src/core/sock/sockinfo.h
- src/core/sock/sockinfo_tcp.cpp
- src/core/util/wakeup.h
- src/core/util/wakeup_pipe.h
- tests/gtest/nvme/nvme.cc
- tests/gtest/tcp/tcp_bind.cc
- tests/gtest/tcp/tcp_connect.cc
- tests/gtest/udp/udp_bind.cc
- tests/gtest/udp/udp_connect.cc
Several issues related Socketxtreme or delegated timers
1. Fixed wakeup waiting thread with Socketxtreme mode.
2. Fixed no TCP timers attempt in delegated mode for blocking calls.
3. Enhanced gtest CI to include More socketxtreme tests and delegated timers tests.
Socketxterme/Delegate functionality
1. In case of socketxtreme wakeup method was skipped. wakeup must always be called regardless this is POSIX or socketxtreme API.
2. Added delegated timers attempt in rx_wait_helper method which is called for every blocking API. Thus, solving many scenarios that would hang with delegated timers and blocking calls.
> issue: 3588192 Blocking API hanging with delegated TCP timers

- src/core/dev/cq_mgr_mlx5_strq.cpp
- src/core/dev/rfs_uc.cpp
- src/core/dev/ring_slave.cpp
- src/core/sock/sockinfo_tcp.cpp
Striding RQ specific code of buffer reclaim leads to an infinite loop if the buffer has wrong type.
Fix infinite loop in an error path.
Bugfix.
> issue: 3656233 Fix infinite loop on a broken buffer reclaim

- src/core/dev/buffer_pool.cpp
- src/core/dev/buffer_pool.h
- src/core/dev/rfs_uc_tcp_gro.cpp
- src/core/lwip/pbuf.c
- src/core/lwip/pbuf.h
- src/core/lwip/tcp.c
- src/core/lwip/tcp.h
- src/core/main.cpp
- src/core/proto/mem_buf_desc.h
- src/core/proto/neighbour.cpp
- src/core/proto/xlio_lwip.cpp
- src/core/sock/sockinfo_tcp.cpp
Custom lwip free method is used to free buffers which are not accepted as socket payload. SocketXtreme flow uses default buffer_pool method which bypasses cq_mgr. In a multithreaded application this leads to global lock usage and potential contention in some scenarios.
Use sockinfo_tcp method unconditionally for all TCP RX packets to avoid the global lock.
Use sockinfo_tcp method unconditionally for all TCP RX packets to avoid the global lock.
Performance optimization.
> issue: 3656233 Use tcp_rx_pbuf_free() for SocketXtreme TCP flow

- src/core/dev/net_device_val.cpp
- src/core/dev/ring_allocation_logic.cpp
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/xlio_extra.h
- tests/extra_api/socket_isolation.c
Add socket isolation option to setsockopt() which allows XLIO to isolate specific sockets with some policy.
Currently, XLIO supports SO_XLIO_ISOLATE_SAFE logic which isolates sockets with a separate global thread-safe ring per interface. This allows to work with the sockets in multiple threads in a thread-unsafe configuration (e.g. delegated TCP timers mode).
In the future, SO_XLIO_ISOLATE interface can be extended with other logic.
Add socket isolation option to force thread-safety for specific sockets.
Avoid races in thread-unsafe environment when some sockets need to be used in multiple threads.
> issue: 3698256 Socket isolation feature

- src/core/dev/ib_ctx_handler.cpp
- src/core/dev/net_device_val.cpp
- src/core/dev/qp_mgr.cpp
- src/core/dev/ring_bond.cpp
- src/core/dev/time_converter.cpp
- src/core/event/event_handler_manager.cpp
- src/core/sock/sockinfo_ulp.cpp
- src/core/util/match.cpp
- src/state_machine/sm.cpp
Fix clang-analyzer warnings
Fix clang-analyzer warnings
Code cleanup and ability to use clang-analyzer in manual/automation scripts.
> issue: 3183915 Fix clang-analyzer warnings

- config/m4/utls.m4
- src/core/dev/qp_mgr_eth_mlx5.cpp
- src/core/dev/qp_mgr_eth_mlx5.h
RM: 3705189
DESC: DEK API was changed in dpcp version 1.1.44
Need to update usage of dpcp::dek
> [TLS] Update DEK usage according to dpcp 1.1.44

- .ci/matrix_job.yaml
We would like to run Valgrind test on both dpcp and default targets today when triggering Valgrind tests in CI we only get dpcp target
Issue: HPCINFRA-1115
> issue: 3669712 enable valgrind for all targets

- src/core/lwip/tcp.c
- src/core/sock/sockinfo_tcp.cpp
XLIO return 0 and errno 0 in case of Keep Alive timeout.
Kernel returns -1 and errno ETIMEOUT.
XLIO ignores lwip TIMEOUT error in sockinfo_tcp.
LWIP uses wrong err in case of keep-alive timeout (EABRT).
API correctness
> issue: 3664594 Return ETIMEDOUT err for timed out socket

- src/core/util/sys_vars.cpp
PRM allows minimum of 512 RX strides per WQE.
Adjust minimum value for NGINX master process from 32 to 512.
Using also minimum stride size allowed - 64 instead of 512.
> issue: 3704820 Fix strides in WQE for NGINX master

- src/core/lwip/tcp.c
- src/core/lwip/tcp_in.c
- src/core/lwip/tcp_out.c
1. Use last_unsent and last_unacked instead of iterating queues.
2. Fix incorrect values for last_unsent and last_unacked.
> issue: 3678579 Fix last_unsent and last_unacked

- src/core/dev/net_device_val.cpp
- src/core/dev/net_device_val.h
- src/core/dev/ring_allocation_logic.cpp
- src/core/dev/ring_allocation_logic.h
- src/core/proto/dst_entry.cpp
- src/core/proto/neighbour.cpp
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/xlio_extra.h
This is leftover from the Multi Packet RQ removal. In current code, this option doesn't have effect and only wastes 96 bytes per socket.
Also, reduce ring_allocation_logic size (64 bytes per socket).
Remove SO_XLIO_RING_USER_MEMORY and related code.
Code cleanup and reduce socket size.
> issue: 3690535 Remove SO_XLIO_RING_USER_MEMORY

- src/core/sock/sockinfo_tcp.h
- src/core/xlio_extra.h
Enum with underlying type is C++ or C23 feature. Move the enum definition to an internal header, because currently, it's unused in public API.
Move C++/C23 enum from the public header to an internal.
Fix compilation of some C programs which use extra API.
> issue: 3786434 Remove C23 feature from public xlio_extra.h

- src/core/dev/ib_ctx_handler.cpp
The false positive warning is generated during linking phase. Cast array size to 32bit type to suppress the warning.
The warning appears in --enable-lto configuration likely due to inlined new[] operator and generated to the underlying malloc() call.
Fix false positive warning.
Fix false positive warning.
> issue: 3792731 Fix -Walloc-size-larger-than warning

- src/core/dev/cq_mgr_rx.h
Accessing completion event channel for dummy RQ,
that was created automatically by ibv when we create QP.
> issue: 3514044 Fix null pointer dereference

- src/core/dev/hw_queue_rx.cpp
- src/core/dev/time_converter_rtc.cpp
- src/core/event/event_handler_manager.cpp
- src/core/event/netlink_event.cpp
- src/core/infra/DemoSubject.h
- src/core/lwip/cc_cubic.c
- src/core/netlink/test_main.cpp
- src/core/proto/dst_entry.cpp
- src/core/proto/dst_entry.h
- src/core/proto/dst_entry_tcp.cpp
- src/core/proto/dst_entry_udp.cpp
- src/core/proto/ip_frag.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/stats/stats_printer.cpp
- src/stats/stats_reader.cpp
- src/vlogger/vlogger.h
cppcheck-2.13 generates new warnings. Current PR fixes majority of them.
Fix cppcheck warnings
Fix cppcheck warnings
> issue: 3813802 Fix warnings from newer cppcheck

- .ci/dockerfiles/Dockerfile.rhel8.6
- .ci/matrix_job.yaml
- contrib/jenkins_tests/cppcheck.sh
- contrib/jenkins_tests/tidy.sh
We're going to move static tests from a dedicated server to docker containers to reduce CI timings 
Switch Cppcheck, Csbuild and Tidy steps of the CI to run in docker containers in a parallel mode
CI currently takes too long, a majority of the time is consumed by static tests running on a physical machine
> issue: HPCINFRA-1321 Switch cppcheck to a docker

- src/core/dev/ring_slave.cpp
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo.h
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/sock/sockinfo_udp.cpp
- src/core/sock/sockinfo_udp.h
- src/core/xlio_extra.h
- src/utils/lock_wrapper.h
This PR is based on PR 110 (issue: 3777348 Move socket statistics to a global storage)
This PR starts from commit: issue: 3777348 Removing m_flow_tag_enabled check
Avoid unnecessary cache lines access.
Descriptions of each change are in the commits.
Recommend to review by commits.
Improve performance.
> issue: 3777348 Improvements for TCP flow unnecessary cache access.

- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo_tcp.cpp
This issue is introduced in Simplify TCP timers commit of vNext
Another issue that was noticed is with reused sockets statistics pool from Statistics global pool commit.
1. Reused sockets are added more than once to the timer list. . See commit description.
2. Reused sockets initialized statistics incorrectly. See commit description.
Fix reused socket timer registration and statistics.
> issue: 3829626 Fix new TCP timers registration for reused sockets

- src/core/dev/hw_queue_tx.cpp
- src/core/event/delta_timer.cpp
- src/core/lwip/def.h
- src/core/lwip/opt.h
- src/core/lwip/tcp_out.c
- src/core/util/vtypes.h
- src/stats/stats_reader.cpp
Compiler defines `__BYTE_ORDER__` and others, but XLIO uses wrong names in the macros. Preprocessor replaces undefined names with 0, so XLIO always builds little endian branch.
Fix the byte order names and fail a build if `__BYTE_ORDER__` is not defined. Otherwise, the build would be broken on a big endian system.
Use correct names for the byte order macros.
Fix build on a big endian system.
> issue: Fix big endian build

- src/core/dev/allocator.cpp
- src/core/dev/allocator.h
- src/core/dev/ring.cpp
- src/core/dev/ring.h
- src/core/dev/ring_simple.cpp
- src/core/event/poll_group.cpp
- src/core/event/poll_group.h
- src/core/main.cpp
- src/core/sock/sock-extra.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/util/hugepage_mgr.cpp
- src/core/util/hugepage_mgr.h
- src/core/xlio.h
- tests/extra_api/xlio_socket_api.c
XLIO socket API is a performance oriented API.
Note, rebased on top of #115
Begins at `issue: 3788369 Remove m_required_send_block introduced by NVME offload`
Productization of the 1st drop.
Productization of the 1st drop.
> issue: 3788369 Second drop of Storage / XLIO socket API

- src/core/sock/sockinfo_tcp.cpp
Iterate over std::list of TCP sockets while
erasing socket during iteration.
Overcomed by increasing iterator before erase.
> issue: 3829626 Fix seg fault in TCP timers

- src/core/dev/hw_queue_tx.cpp
- src/core/dev/hw_queue_tx.h
- src/core/ib/mlx5/ib_mlx5.cpp
- src/core/ib/mlx5/ib_mlx5.h
rdma-core limits number of UARs per context to 16 by default. After
creating 16 QPs, XLIO receives duplicates of blueflame registers for
each subsequent QP. As results, blueflame doorbell method can write WQEs
concurrently without serialization and this leads to data corruption.
BlueFlame can make impact on throughput since copy to the blueflame
register is expensive. It can improve latency in some low latency
scenarios, however, XLIO targets high traffic/PPS rates.
Removing blueflame method slightly improves performance in some
scenarios.
BlueFlame can be returned in the future to improve low-latency
scenarios, however, it will need some rework to avoid the data
corruption.
Remove BlueFlame doorbell method
Fix data corruption for multi-threaded applications with over 16 QPs. Minor …
> issue: 3818038 Remove BlueFlame doorbell method

- src/core/lwip/tcp_out.c
When send window is not big enough for the required TCP segment to send, we may split the segment so it will fir into the window. Before this change - We didn't split the segment in the case we have unacked segments. The motivation was that we anticiapte to get ACK on the inflight segments, which will trigger the next send operation.
This flow count on RTT for receiving ACKs, which may be delayed depending on the remote side. When RTT is long - we would block sending although TCP send window allows it.
The change is to split TCP segments although we have unacked data, in case the send window is big enough (mss).
> issue: 3795997 Allow split segment with unacked q

- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
Avoid calling register_socket_timer_event when a socket is already registered (TIME-WAIT). Although there is no functionality issue with that, it produces too high rate of posting events for internal-thread. This leads to lock contention inside internal-thread and degraded performance of HTTP CPS.
HTTP CPS degradation.
> issue: 3844385 Fix new TCP timers registration lock contention

- src/core/sock/sockinfo_tcp.h
- src/core/sock/sockinfo_ulp.cpp
UTLS uses tcp_tx_express() for non blocking sockets. However, this TX method doesn't support XLIO_RX_POLL_ON_TX_TCP. Additional RX polling improves scenarios such as WEB servers.
Insert RX polling into UTLS TX path to resolve performance degradation.
Fix RX poll on TX option for UTLS.
Resolve performance degradation.
> issue: 3788164 Fix RX poll on TX option for UTLS

- src/core/dev/ring_simple.cpp
- src/core/main.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
Added new env parameter - XLIO_MAX_TSO_SIZE.
It allows the user to control the maximum size of TSO, instead of taking the maximum cap by HW.
The default size is 256KB (maximum by current HW).
Values higher than HW capabilities won't be taken into account.
> issue: 3795997 Control TSO max payload size

- src/core/main.cpp
- src/core/sock/sock_stats.cpp
- src/core/sock/sock_stats.h
- src/core/sock/sockinfo_tcp.cpp
When sock_stats was static its destructor was called before xlio_exit that destroys the internal-thread which destroys sockets. 
We should avoid having global objects with untrivial constructors/destructors, since there is no control of their execution order. 
Functionality
> issue: 3858121 Fixing socket stats corruption on termination

- src/core/dev/ring_simple.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/util/xlio_stats.h
- src/stats/stats_reader.cpp
When TCP socket is destroyed it frees the preallocated buffers after dst_entry is deleted. This returns the buffers to the global pool directly and breaks m_tx_num_bufs,m_zc_num_bufs ring counters.
1. Move the preallocated buffers cleanup before dst_entry destruction.
2. Add ring stats for m_tx_num_bufs and m_zc_num_bufs.
Functionality
> issue: 3854806 Fixing TX buffers return order in TCP socket destruction

- src/core/util/sys_vars.cpp
Parameters XLIO_TX_BUFS and XLIO_RX_BUFS are deprecated and will be removed in the future.
Print a deprecation warning if user sets XLIO_TX_BUFS or XLIO_RX_BUFS.
Warn user about future parameters removal.
> issue: 3832212 Print a deprecation warning for XLIO_TX/RX_BUFS

- .ci/matrix_job.yaml
We'd like to run the XLIO CI in ubuntu-24.04-containers
add Dockerfiles for ubuntu-24.04, add corresponding section in matrix_job.yaml
[Feature Request #3914591](https://redmine.mellanox.com/issues/3914591)
> [CI] Add ubuntu-24.04 support

- README
Correct the default value of XLIO_UTLS_RX. Force a single convention for Enabled/Disabled .
Correct the default value of XLIO_UTLS_RX. Force a single convention for Enabled/Disabled .
Tidy up the documentation.
> issue: tidy up the default values in README

- src/core/lwip/err.h
- src/core/lwip/opt.h
- src/core/util/vtypes.h
cppcheck skips most of the files from scanning and returns successfully. This potentially hides issues that can be detected in CI.
Replace `#error` with `#warning` in the endianness check to allow cppcheck to find a working configuration.
`#warning` still fails the compilation process, so we won't miss a wrong endianness configuration.
Replace `#error` with `#warning` in the endianness check to allow cppcheck to find a working configuration.
Fix cppcheck job in CI.
> issue: 3875155 Fix cppcheck skipping files from scanning

- .ci/matrix_job.yaml
- contrib/jenkins_tests/style.conf
- contrib/jenkins_tests/style.sh
- src/core/ib/base/verbs_extra.cpp
- src/core/infra/DemoObserver.cpp
- src/core/infra/sender.cpp
- src/core/netlink/test_main.cpp
- src/core/util/chunk_list.h
- src/core/util/sys_vars.cpp
- src/utils/asm-arm64.h
- tests/gtest/core/xlio_sockopt.cc
- tests/gtest/mix/mix_list.cc
- tests/gtest/sock/sock_socket.cc
- tests/gtest/tcp/tcp_accept.cc
- tests/gtest/tcp/tcp_connect.cc
- tests/gtest/tcp/tcp_connect_nb.cc
- tests/gtest/tcp/tcp_event.cc
- tests/gtest/tcp/tcp_rfs.cc
- tests/gtest/tcp/tcp_send.cc
- tests/gtest/tcp/tcp_sendto.cc
- tests/gtest/tcp/tcp_socket.cc
- tests/gtest/tcp/tcp_sockopt.cc
- tests/gtest/udp/udp_connect.cc
- tests/gtest/udp/udp_recv.cc
- tests/gtest/udp/udp_rfs.cc
- tests/gtest/udp/udp_send.cc
- tests/gtest/udp/udp_sendto.cc
- tests/gtest/udp/udp_socket.cc
- tests/gtest/xliod/xliod_bitmap.cc
- tests/gtest/xliod/xliod_hash.cc
Starting from clang-format-15, it supports forced brackets insertion. With this feature we no longer need clang-tidy CI job and all the coding style can be checked more conveniently.
Note, It's rebased on top of #119 which moves the CI job to clang-16.
Move to clang-format-16
Brackets insertion support and use more modern clang version which is easier to find in Linux distributions.
> issue: HPCINFRA-1798 Update code base to clang-format-16 style

- src/core/proto/mem_buf_desc.h
- src/core/sock/sock-extra.cpp
- src/core/sock/sockinfo_tcp.cpp
Bugfixes:
- Send operations in ESTABLISHED event callback
- Buffer metadata corruption on xlio_buf::userdata usage
Bugfixes
Bugfixes
> issue: 3947690 Storage API bugfixes

- src/core/event/poll_group.cpp
- src/core/main.cpp
- src/core/sock/fd_collection.h
Add XLIO sockets to the fd_collection array, but bypassing all the internal logic. This allows ring_slave to find socket object for the flow tag feature.
Add flow_tag support for new XLIO socket API
Performance improvement
> issue: 3947680 Add flow_tag support for new XLIO socket API

- src/core/iomux/epoll_wait_call.cpp
- src/core/proto/mem_buf_desc.h
The recent xlio_list change introduced a bug into epoll ready list iteration: a socket can be removed from the list before getting the next item. This leads to iteration over a removed item causing endless loop.
As a fix, remember 'si_next' before removing a socket from the list.
Also align mem_buf_desc_t to the cache line boundary.
Fix epoll ready list iteration
Bugfix.
> issue: 3933912 Fix epoll ready list iteration

- src/core/util/utils.cpp
- src/core/util/utils.h
At startup, XLIO tries to read files in the /proc/sys/net/core/ directory, which can be inaccessible when running in a container (it doesn’t matter whether in privileged mode or not).  In this case, XLIO produces ERROR messages which can be considered as WARNINGs.
This commit changes the default log severity in the read_file_to_int() function from VLOG_ERROR to VLOG_WARNING. This is done to account for different container configurations where certain files may not be accessible, while ensuring a default value is used for every parameter. This change enhances XLIO's adaptability in various container environments.
This breaks CI and blocks the integration with DOCA.
> issue: 3958757 Change error message to warning when reading FS files

- .ci/Jenkinsfile
- .ci/matrix_job.yaml
BlackDuck scan fails due to ngci connecting to the old gerrit url, fix is made to both this repo and the ci-demo repo (Changes made in this PR: https://github.com/Mellanox/ci-demo/pull/90)
Add credentialsId to login into the new gerrit url
skipDockerDaemonCheck configuration provided by the gerrit team.
Issue: HPCINFRA-2289
> [Blackduck] Bugfix - ngci connecting to the wrong url

- contrib/jenkins_tests/cov.sh
- src/core/config_scanner.c
- src/core/dev/ring_allocation_logic.cpp
- src/core/dev/ring_allocation_logic.h
- src/core/dev/ring_simple.cpp
- src/core/event/delta_timer.cpp
- src/core/event/event_handler_manager.cpp
- src/core/event/event_handler_manager.h
- src/core/lwip/tcp.c
- src/core/proto/flow_tuple.cpp
- src/core/proto/neighbour.h
- src/core/proto/neighbour_table_mgr.cpp
- src/core/sock/fd_collection.cpp
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_udp.cpp
- src/core/util/hugepage_mgr.cpp
- src/core/util/ip_address.h
- src/core/util/sys_vars.h
- src/core/util/utils.cpp
- src/core/util/xlio_stats.h
- src/stats/stats_data_reader.h
- src/stats/stats_reader.cpp
- src/utils/lock_wrapper.h
- tools/daemon/daemon.c
- tools/daemon/flow.c
- tools/daemon/notify.c
- tools/daemon/tc.c
- tools/daemon/tc.h
We're requested to upgrade the Coverity version to 2023.12
The PR runs Coverity v2023.12 against the Xlio codebase
> issue: HPCINFRA-1734 [CI] Coverity: upgrade to v2023.12

- src/core/dev/ring_slave.h
Fixes latency degradation caused by the reduced size of xlio_list.
It created a gap in the ring class which is not cache line aligned.
Added padding bytes to align it to a full cache line.
> issue: 3964910 Align ring size to cache line

- src/core/dev/hw_queue_tx.cpp
- src/core/event/poll_group.cpp
- src/core/proto/xlio_lwip.h
- src/core/sock/sockinfo_tcp.cpp
TX polling can trigger a zerocopy completion event. If this happens in
context of xlio_poll_group_flush(), a send operation can break
consistency between socket dirty status and their group's dirty list.
To avoid the issue, don't poll TX outside the xlio_poll_group_poll()
context. This will make the zerocopy completion events possible only
from the polling context.
If a dirty socket is closed without a flush, it must be removed from the
group's dirty list. Otherwise, this can lead to a use-after-free issue.
Avoid TX polling in XLIO Socket flush. Remove leftover closed socket from the dirty list.
XLIO Socket API Bugfixes.
> issue: 3976537 Avoid TX polling in XLIO Socket flush

- src/core/dev/hw_queue_tx.cpp
- src/core/dev/hw_queue_tx.h
- src/core/dev/ring_simple.h
- src/core/util/xlio_stats.h
- src/stats/stats_reader.cpp
TSO statistics are very important for tracking TX performance. 
Two variables are added, TSO packets number and TSO bytes number. With these two and with conjunction of total TX packets and bytes, the needed information can be derrived.
Statistics and performance visibility
> issue: 3807308 Add Ring TSO statistics

- src/core/util/xlio_list.h
Starting from gcc-14, it generates template-id-cdtor error on a constructor with a template id.
Fix gcc-14 build.
Fix gcc-14 build.
> issue: 3949975 Fix -Wtemplate-id-cdtor in xlio_list

- src/core/proto/header.cpp
Need to add the length of VLAN header
to L2 header length in case of VLAN tagged
packets, the issue was only in send to neigh flow
when neigh is not resolved yet
> issue: 3777769 Fix No traffic with VLAN tagged packets

- src/vlogger/vlogger.cpp
Early logs can be printed before vlogger subsystem initialization. If they are printed to stdout, this can interfere with tools that parse output, such as grep, awk, etc.
Gtest calls a subshell command to find a default gw and early logs breaks this functionality. Example of such scenario is a container with prohibited read access to sysfs files which XLIO reads.
Print early logs to stderr
Fix gtests when early logs are printed and avoid interference with parsing tools.
> issue: 3981627 Print early logs to stderr

- .ci/matrix_job.yaml
LibXLIO CI definition under job_matrix.yaml has the credentials of rivermax which do not have permissions to pull docker images needed to build LibXLIO docker images
Fix issue with libxlio CI being unable to build new images
Credentials under matrix_job.yaml set to registry_auth are incorrect
Change harbor credentialsID under matrix_job.yaml to one with permissions over libxlio docker images
> [CI] BUGFIX - CI job fails to build new dockers

- src/core/dev/rfs_uc.cpp
- src/core/sock/sock-app.cpp
- src/core/sock/sock-app.h
- src/core/sock/sockinfo.cpp
Add support for UDP reuse port for listen socket for both IPv4 and IPv6 at the same conf file.
> issue: 3784248 Nginx UDP reuseport for IPv6

- src/core/event/event_handler_manager.cpp
Base class event_handler_manager closes m_epfd unconditionally in the destructor. But in case of local copy, the constructor exits early and leaves m_epfd initialized as 0.
This leads to closing 0 file descriptor during the local copy destruction what causes runtime issues for objects related to the fd 0.
Don't close epfd in event_handler_manager_local destructor.
Fix closing of a wrong file description what causes runtime issues.
> issue: 3976544 Don't close epfd for event_handler_manager_local

- .ci/matrix_job.yaml
Blackduck module report output shows the wrong version
Change blackduck input to match branch selected instead of static `0.1.0`
Bugfix for blackduck report
> Issue: [Bugfix] blackduck reports wrong version

- src/core/dev/allocator.cpp
- src/core/dev/allocator.h
- src/core/dev/buffer_pool.cpp
- src/core/dev/buffer_pool.h
- src/core/dev/cq_mgr_rx.cpp
- src/core/dev/cq_mgr_rx.h
- src/core/dev/net_device_val.cpp
- src/core/dev/ring_simple.cpp
- src/core/dev/ring_simple.h
- src/core/proto/mapping.cpp
- src/core/proto/mapping.h
Based on PR154.
Adding doca_mmap support:
1. Accessed by get_doca_mmap().
2. Add doca_mmap support for sendfile.
3. Still using lkey by ibv mem_reg to allow traffic during integration.
> [DOCA] Add doca_mmap support for memory registration

- tests/gtest/common/sys.cc
sys_str2addr() converts a string address representation to the sockaddr
structure. However, an invalid address sets either AF_INET or AF_INET6
address family and returns corrupted IP portion of the sockaddr object.
Return AF_UNSPEC address family in case of an invalid IP address. So,
default gateway detection can handle address parsing.
Invalid port portion is still silently ignored. In the future, the
function should return the conversion status and this needs to be
handled explicitly by the function users.
sys_gateway() converts string address to a temporary sockaddr object
on stack before changing the result object. However, a different
uninitialized object is checked for the conversion status.
Check the correct object.
Fix default gateway detection.
Fix incorrect gateway detection in …
> issue: 3981627 [GTEST] Fix default gateway detection

- README
- src/core/dev/buffer_pool.cpp
- src/core/dev/buffer_pool.h
- src/core/main.cpp
- src/core/util/xlio_stats.h
- src/stats/stats_reader.cpp
XLIO_PRINT_REPORT now prints all the buffer pools reports unconditionally and shows number of the expands.
xlio_stats prints also "in use" buffers along with the free buffers. There total number of allocation buffers is "in use" + "free".
Improve buffer pools statistics and report.
User experience and system observability improvements.
> issue: 3928453 Improve buffer pools statistics and report

- .ci/do_release.sh
- .ci/dockerfiles/Dockerfile.rhel8.6.release
- .ci/matrix_job.yaml
- .ci/opensource_jjb.yaml
- .ci/pipeline/release_jjb.yaml
- .ci/pipeline/release_matrix_job.yaml
Until now, release process is done manually by the dev team. This process involves creating a tag on a commit that needs to be released, building that tag and copying the files to NFS location
The idea is to create a jenkins pipeline that will do the entire process with given inputs, This commit will commence phase 1 - doing the build and copying of packages created to NFS.
THE CREATION OF A RELEASE TAG ON A COMMIT IS NOT PART OF THIS PR
Add release_jjb and the corresponding matrix file for a new pipeline definition, the release is run on rhel8.6
Add ARG HARBOR_URL to dockerfile, to support DRP in the future since the release process needs to run there as well
Change do_release.sh script to match the new parameters provided by the jenkins job …
> issue: HPCINFRA-776 [CI] Release pipeline

- README
- src/core/main.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
Remove the XLIO_BF parameter as a leftover.
BlueFlame support has been removed. Besides, XLIO_BF was unused and an rdma-core specific env parameter was checked instead.
Remove the XLIO_BF parameter.
Unused parameter.
> issue: 3928006 Remove unused XLIO_BF

- .ci/matrix_job.yaml
We're going to remove Ubuntu 20.x branches from CI
We're going to remove Ubuntu 20.x branches from CI
[HPCINFRA-2183 xlio: OS Support Matrix for July release](https://jirasw.nvidia.com/browse/HPCINFRA-2183)
> [CI]: Remove the Ubuntu-20.x support

- .ci/do_release.sh
The new release pipeline links the latest release to a file called latest.txt, the dev team requested this feature to be removed
Remove echo line from do_release script into latest.txt
Requested by the dev team
> [CI] Remove latest file from release script

- .ci/dockerfiles/Dockerfile.rhel8.6
We need to update the EPEL repository for our RHEL8-based CI branches
Change the location of pkg repository for RHEL8-based builds
The Fedora Project, who maintains and distributes EPEL repository for RHEL/Centos has recently moved it to different location
> HPCINFRA-2456 update EPEL7 source 

- src/core/lwip/tcp.h
- src/core/lwip/tcp_in.c
- src/core/lwip/tcp_out.c
1. Fix ACK of partial TSO segment:
In the happy TSO path whenever we get an ack, we go over
the unacked list and shrink TSO segments accordingly.
The issue is when we get the ack after retransmission where
the segment/s move from the unacked list to unsent.
In this case, we don't shrink segments in the unsent list.
a. Shrink is done for all segments now, not only TSO
b. Avoid the corner case when partially ACKed and not shrunk segments block TCP progress.
2. Fix unsent queue after fast retransmission+RTO:
In fast retransmission, we move a single segment from the unacked list to the unsent list.
But if we have RTO right after, we move all the unacked list to the unsent list, but we don't
take into consideration the we might have a retransmitted segment already in the unsent list.
Example: …
> Partial ack TSO after retransmission + Fix TCP segments order in RTO after fast retransmission

- src/core/event/event_handler_manager_local.cpp
- src/core/event/event_handler_manager_local.h
- src/core/lwip/tcp.h
- src/core/lwip/tcp_in.c
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- tests/python_tests/misc/send_raw_packet.py
Seg fault fix for delegated timers and cleanups
See commit comments. 
Crash fix for Nginx Proxy
> issue: 3594311 Fix segfault for delegate incoming handshake failure 

- src/core/proto/dst_entry_udp_mc.cpp
- src/core/proto/route_entry.cpp
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo.h
Fixing device unregistration errors in socket cleanup
See Commit message 
Fixing socket cleanup
> issue: 4043152 Removing redundant net_dev_entry registration socket

- src/core/sock/sock-redirect.cpp
- src/core/sock/sock_stats.cpp
- src/core/sock/sock_stats.h
- src/core/sock/sockinfo.cpp
- src/core/sock/sockinfo.h
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/sock/sockinfo_udp.cpp
- src/core/sock/sockinfo_udp.h
- src/core/sock/sockinfo_ulp.cpp
- src/core/util/data_updater.cpp
Fixing XLIO crash with thread_local stats object
The thread_local objects are deallocated once the thread is finished.
Depending on the configuration sockets can use a pointer to a thread_local stats object.
If that thread is finished but the socket is still alive, XLIO will try to access deallocated stats object and hit seg fault.
Crash fix
To make things straight forward we always ask if stats object exists. This should also be the most efficient. No more thread_local or global dummy object. 
> issue: 4039462 XLIO crashes on thread_local stats

- .ci/matrix_job.yaml
- contrib/test_jenkins.sh
A fixup for cppcheck step in CI, which doesn't work as expected
_Subject: 
A fix for CI, which doesn't call cppcheck, when DPCP/DOCA compilation is not requested
_Justification for the PR. 
cppcheck step doesn't do any job when DOCA / DPCP support is not requested
> issue: HPCINFRA-2413 [CI] cppcheck step fixup

- README
- src/core/dev/ring_slave.cpp
- src/core/main.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
This adds support of a TCP steering which matches only destination IP. It can be used with a big number of outgoing connections when they exceed the steering root table limit.
For proper and optimal work, user needs to guarantee a unique IP per ring.
Overcome 64K steering limitation for outgoing connections with a SW implementation.
Create over 64K outgoing connections.
> issue: 4021863 Add XLIO_TCP_2T_RULES

- src/core/lwip/tcp.c
- src/core/lwip/tcp_in.c
Sockets that were closed after TCP RST didn't gerenate event.
Related to issue 3594311, presented by commit d289cdc8.
> issue: 4071902 Fix notifications after RST

- .ci/matrix_job.yaml
- .ci/opensource_jjb.yaml
We update references to Jenkins's secrets
We update CI with updated Jenkins secrets references
Secrets Scanner does not work correctly with the old secrets format
> [CI]: fixing false positives in the Secrets Scanner on doca_xlio_vNext branch

- .ci/matrix_job.yaml
This change fixes the intermittent BlackDuck failures in CI jobs
Replace the NGCI docker image used for the BlackDuck module 
The old NGCI image is old and not supported by the Lab Infrastructure team
> HPCINFRA-2665: [CI] Fix BlackDuck issues

- src/core/sock/sockinfo.h
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/sock/sockinfo_udp.cpp
- src/core/sock/sockinfo_udp.h
- src/core/sock/sockinfo_ulp.cpp
After clearing the RX buffer, we need to reset all related state, including m_rx_pkt_ready_offset, to ensure consistency of the state.
> issue: 4039879 Reset m_rx_pkt_ready_offset after clearing RX buffer

- src/core/dev/net_device_table_mgr.cpp
- src/core/util/ip_address.h
In this commit, we address a scenario where more than one network interface is assigned the same IP address. The current implementation supports creating RX rules for only one interface per IP address, which can lead to issues if multiple interfaces share the same IP.
Key Changes:
Added a mechanism to detect when the same IP address is assigned to multiple interfaces.
If this conflict occurs, a warning message is printed to notify the user that this configuration is not supported.
When faced with this conflict, the implementation now prioritizes the interface that is in the "Up" state, assigning the RX rules to it.
This change helps prevent potential conflicts and ensures that the most relevant (active) interface is used when an IP address conflict occurs.
What kind of change does this PR …
> issue: 4023262 Handle down interface states during table update

- src/core/dev/cq_mgr_rx.cpp
- src/core/dev/cq_mgr_rx_regrq.cpp
- src/core/dev/cq_mgr_rx_strq.cpp
- src/core/dev/cq_mgr_tx.cpp
- src/core/dev/cq_mgr_tx.h
- src/core/dev/net_device_val.cpp
- src/core/ib/base/verbs_extra.h
We always create CQs that cannot overflow. Therefore, we can use flag IBV_CREATE_CQ_ATTR_IGNORE_OVERRUN and avoid updating dbrec. HW will ignore the consumer index and this will save a memory barrier per successful polling.
Don't update CQ consumer index. Create CQs with IBV_CREATE_CQ_ATTR_IGNORE_OVERRUN flag.
Performance optimization.
> issue: 4124248 Don't update CQ consumer index

- src/core/dev/hw_queue_rx.cpp
- src/core/dev/hw_queue_tx.cpp
- src/core/dev/ib_ctx_handler.h
Using DOCA API to distribute interrupts to different completion vectors.
Setting different completion vectors to different contexts spreads the CPU load more evenly.
We use DOCA API to associate different workers with different completion vectors to improve performance.
Using DOCA API to distribute interrupts to different completion vectors.
Fixing issue 4144195 and improving performance.
1. Inspecting changes in `/proc/interrupts` to verify the distribution - verified successfully.
2. Inspecting RPS and TP - no improvement and no degradation.
3. Inspecting CPS - 
- cps improvement for 0B download test - 13%.
- recurring degradation for 100KB download - between 3% to 5% across different runs.
4. Inspecting CPU - no degradation.
> issue: 4144195 MSIX distribution

- README
- src/core/main.cpp
- src/core/util/hugepage_mgr.cpp
- src/core/util/hugepage_mgr.h
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
In a containerized environment mmap() beyond the hugepages limit can be successful, but a further memory access triggers SIGBUS and terminates the process. Check that all the allocated hugepages are resident with mincore() to avoid the SIGBUS issue.
Cost of the feature depends on the allocation size and hugepage size:
- 32GB with 2MB pages takes 4400 us
- 32GB with 1GB pages takes 11 us
- 32MB with 2MB pages takes 5-6 us
We expect a big memory preallocation at the start (2GB by default) and
rare 32MB allocations during warmup period. Therefore, this feature can
add several additional 5us latency spikes during warmup period.
Check for resident hugepages after allocation.
Avoid SIGBUS in containerized environments.
> issue: 3884801 Check for resident hugepages to avoid SIGBUS

- src/core/dev/cq_mgr_tx.cpp
- src/core/dev/hw_queue_tx.cpp
- src/core/dev/ring.h
- src/core/dev/ring_bond.cpp
- src/core/dev/ring_bond.h
- src/core/dev/ring_simple.cpp
- src/core/dev/ring_simple.h
- src/core/proto/dst_entry.cpp
- src/core/proto/dst_entry.h
- src/core/proto/dst_entry_tcp.cpp
- src/core/proto/dst_entry_tcp.h
- src/core/proto/dst_entry_udp.cpp
- src/core/proto/neighbour.cpp
- src/core/sock/sockinfo.h
1. Removed DOCA code from CQ mgr TX - CQ mgrs are planned to be removed
2. Removed mem_buf_tx_get inner polling   
3. Removed debug only variable in data path
Inner polling inside mem_buf_tx_get tries to mitigate bad app behavior or misconfiguration. 
XLIO focuses on HPC apps and it is better to avoid such unnecessary logics.
Additionally, the implementation introduces a race in working with notification mechanism.
> issue: 4159515 Removing DOCA code from cq_mgr_tx

- README
- src/core/dev/hw_queue_tx.cpp
- src/core/dev/hw_queue_tx.h
- src/core/main.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
Using DOCA terminology to implement the equivalent to SW queue limits.
Limit the amount of TX task pool expansions.
Solve https://redmine.mellanox.com/issues/4158085.
Utilizing the existing DOCA mechanisms for task pool limits and expansions, the following designs were evaluated:
1. A limit based on WQEBBs.
2. A limit based on in-flight bytes.
Both approaches required code duplication with doca_ether. Leveraging the existing DOCA task pool limitation mechanism achieves similar results without reinventing the wheel, albeit with reduced granularity and control.
> issue: 4158085 DOCA TX credits

- .ci/pipeline/dr_weekly_jjb.yaml
- .ci/pipeline/dr_weekly_matrix.yaml
This change implements weekly builds on the DR site
weekly_laucher Job that stays unchanged and triggers the release job on the DR site
We need to do periodic checks of DR Jenkins instance and Infra entities by running CI workloads
weekly_laucher scheduled job
> [CI]: Implement weekly builds on DR site

- .ci/matrix_job.yaml
- .ci/pipeline/xlio_doca_ci_jjb.yaml
vNext CI job is limited to 1 concurrent build due to the limitation of beni09 environment.
On doca_xlio branch we use containers, and we can run in parallel to increase productivity.
Create new jjb file for the new job definition
Run parallel CI runs
Add new separate CI job just for doca_xlio branch
> [CI] issue:HPCINFRA-3085 seperate Doca CI from Xlio CI

- .ci/opensource_jjb.yaml
We have separate CI job for doca_xlio branch, we want to avoid running vNext CI job on doca_xlio branch changes
Do not trigger CI on doca_xlio branch changes
No need to trigger both jobs
Add doca_xlio branch to branch blacklist in GH pull request plugin definition
> [CI] Block CI triggers from doca_xlio_vnext branch

- .ci/dockerfiles/Dockerfile.ol9.4
- .ci/matrix_job.yaml
- .ci/opensource_jjb.yaml
- .ci/scripts/doca_install.sh
Add new OS support to CI
Oracle Linux 9.4
As per requests: [HPCINFRA-2897](https://jirasw.nvidia.com/browse/HPCINFRA-2897), [#4063495](https://redmine.mellanox.com/issues/4063495)
> HPCINFRA-2897: Add ol9.4 support in CI

- src/core/dev/cq_mgr_tx.cpp
- src/core/proto/mem_buf_desc.h
- src/core/sock/sockinfo_tcp.cpp
In case we got an ECQE - set the socket in a closing state. Effectively this sends a TCP-RST.
Currently, in case we got an ECQE - we don't notify our callers we got to an invalid state.
The callers will keep trying to transmit TX segments, unaware of any issues.
This causes callers to not be able to identify and overcome error states, causing issues like 4183221.
Propagates the pcb to sq_wqe_prop, so when getting an ECQE - we could notify the TCP/IP stack.
1. Tested sockperf gets correct error + errno
2. Tested xlio_socket_api.c test gets correct error
> issue: 4183221 propagate socket errors

- src/core/dev/cq_mgr_tx.cpp
- src/core/dev/cq_mgr_tx.h
dump wqe's content for further debug in case of ecqe.
Following https://redmine.mellanox.com/issues/4183221
We created a patch to dump the wqe that had the invalid state.
No reason to not have it in our vNext as well.
Further debug ability.
> issue: 4203242 dump wqe to log in case of ecqe

- .ci/matrix_job.yaml
We want to move all build steps and test CI steps to the Blossom K8s cluster.
Switch to the Blossom K8s cluster.
Blossom cluster is more stable, visibly managed and has 24/7 SRE/NOC support.
> [CI] issue: HPCINFRA-3180 Move build steps to Blossom K8s

- src/core/lwip/tcp_in.c
- src/core/sock/sockinfo_tcp.cpp
This fixes 2 bugs that lead to a crash if combined:
1. ip_output() converts a pbuf object from stack to mem_buf_desc_t which leads to reading of garbage;
2. Acknowledging all the data in a FIN segment but not the FIN flag itself leads to removing all the pbufs from the segments and NULL pointer dereference at the end.
Fix a crash.
Bugfixes.
> issue: 4287937 Fix a crash on shrinking a FIN segment with data

- src/core/dev/cq_mgr_rx_regrq.cpp
- src/core/dev/cq_mgr_rx_strq.cpp
- src/core/dev/cq_mgr_tx.h
- src/core/dev/ring_slave.cpp
According to the PRM - section 8.20.3.2:
"After seeing that the CQE is in SW ownership, 
SW should do memory barrier and re-read the CQE."
It was removed as part of commit 88436b2 - 
causing us to sometimes observe “garbage” data.
This commit returns the barrier as needed.
This patch adds a sync memory barrier as needed by the PRM, ensuring that any data we fetch after getting a CQE is correct and valid by the time we read it.
Kept a debug trace I added along the way which I think could be useful.
Without conforming to the PRM, we are on the grace of our prefetch calls.
• Prefetch instructions may not complete before the actual load, especially under high concurrency or specific timing.
• This timing discrepancy has caused us to observe uninitialized or “garbage” data on verification …
> Issue #4308042: Fix read of invalid data from CQE

- src/core/sock/sockinfo.cpp
empty() is thread safe - remove reduandant lock.
issue: 4379306 Remove reduandant lock
> issue: 4379306 Remove reduandant lock

- .ci/blackduck_source.sh
- .ci/dockerfiles/Dockerfile.rhel8.6
- .ci/matrix_job.yaml
Replaced NGCI-based BlackDuck source scan with custom BlackDuck script execution
This change removes the NGCI module previously used for running BlackDuck source scans and replaces it with a custom script that uses SSH authentication and provides clearer run logs
NGCI relied on a Gerrit user token for cloning BlackDuck, which was subject to frequent rotation and caused recurring CI failures. 
We move to scan execution via a custom script using a service account with stable SSH-based authentication.
> HPCINFRA-3413 BD source scan startup fix

- .ci/matrix_job.yaml
Migrate hardcoded secrets from the CI codebase to Jenkins-managed credentials
We are removing hardcoded secrets and credential references from the CI codebase.
Hardcoded secrets trigger security scan failures and reduce the overall security posture of the system.
By transferring secrets to Jenkins credentials storage and referencing them through environment variables.
> [CI] issue: HPCINFRA-3523 secret scan fix

- src/core/dev/ring_slave.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/utils/lock_wrapper.h
- tests/gtest/tcp/tcp_socket.cc
This change replaces a thread-local dummy locker with a global one in ring_slave.cpp to fix a use-after-free issue.
Replace thread-local dummy locker with a global one in ring_slave.
During XLIO shutdown, when one thread attempts to access a socket's locker that was created by a terminated thread, a use-after-free issue occurs because the thread-local dummy locker object is freed when its creator thread terminates. This can lead to segmentation faults during cleanup.
The solution is straightforward:
1. Replace static thread_local lock_dummy t_lock_dummy_ring with a global static lock_dummy g_lock_dummy_ring
2. Update get_new_lock() to use this global locker
4. The global locker is initialized with a name for better debugging: "global_dummy_ring"
This change ensures the dummy locker …
> issue: 4347777 Replace thread-local dummy lock with global one

- src/utils/rdtsc.h
RTO calculations were producing wrong results over our incorrect TSC-based logic.
We were using /proc/cpuinfo which is not standardized, nor accurate:
https://github.com/htop-dev/htop/issues/953
TSC is also x86 specific and considered unreliable in cases like dynamic frequency scaling.
Hence, we switch to platform clock which is more performant than chrono as can be seen here:
https://gcc.gnu.org/legacy-ml/gcc-help/2019-07/msg00068.html
Fix timers and RTO issues.
Fix https://redmine.mellanox.com/issues/4043235.
> issue: 4043235 TCP_USER_TIMER wrong RTO behavior

- src/core/dev/hw_queue_tx.cpp
Based on PR 321.
Correct special WQEs cleanup.
Fix possible issues and syndroms do to incorrect WQEBB cleanup.
Functionality.
Always nullify the whole first WQEBB
> issue: 4213201 Nullify all WQEBB on special WQEs

- .ci/dockerfiles/Dockerfile.ubuntu22.04
- .ci/matrix_job.yaml
- contrib/jenkins_tests/globals.sh
- contrib/jenkins_tests/vg.sh
Today we use benni09 static agent to run test/gtest/valgrind steps which is unscaleable since it can only run one pipeline at a time, causing delays in builds that can be stuck waiting for hours
The idea is to move these steps to containers, allowing running them in parallel as well as running multiple pipelines at the same time (depending on the capacity of the k8s cluster)
This commit moves Valgrind away from static agent to container running on k8s
Issue: [HPCINFRA-3249](https://jirasw.nvidia.com/browse/HPCINFRA-3249)
Issue: [HPCINFRA-3559](https://jirasw.nvidia.com/browse/HPCINFRA-3559)
> [CI] migrate CI test steps to containers - Valgrind

- .ci/do_release.sh
- contrib/build_pkg.sh
Released packed should be tar.gz instead of src.rpm, with a small change to the dir stucture
Pointers to the new tar.gz file are not being created by the script
Move libxlio.spec to the root of the directory being compressed.
Remove libxlio.spec from contrib/scripts/libxlio.spec
For now we will create both the src.rpm and the tar.gz
created in the build_pkg.sh , and moves it to the release folder.
Issue #4377705
> Issue #4377705: Create tar.gz from src.rpm

- .ci/matrix_job.yaml
Csbuild fails due to issues with some cpp files, which were previously not found in Clang18, but are found in Clang19
Until these issues are resolved, we will use Clang18
Change csbuild docker image
> [CI] issue: HPCINFRA-3635 Use Clang-18 docker image for csbuild

- .ci/dockerfiles/Dockerfile.ubuntu22.04
- .ci/matrix_job.yaml
- contrib/jenkins_tests/test.sh
Today we use benni09 static agent to run test/gtest/valgrind steps which
is unscaleable since it can only run one pipeline at a time, causing
delays in builds that can be stuck waiting for hours
The idea is to move these steps to containers, allowing running them in
parallel as well as running multiple pipelines at the same time
(depending on the capacity of the k8s cluster)
Moves test away from static agent to container running on k8s
[HPCINFRA-3633](https://jirasw.nvidia.com/browse/HPCINFRA-3633)
> [CI] issue: HPCINFRA-3633 Migrate CI test steps to containers - Test

- README
- src/core/config/descriptor_providers/xlio_config_schema.json
- src/core/config/mappings.py
- src/core/iomux/io_mux_call.cpp
- src/core/main.cpp
- src/core/util/sys_vars.cpp
- src/core/util/sys_vars.h
Remove the deprecated XLIO_SELECT_POLL_OS_FORCE configuration parameter
as it can be fully controlled by XLIO_SELECT_POLL_OS_RATIO and
XLIO_SELECT_SKIP_OS parameters. This aligns with the original repo's
direction to remove this configuration while maintaining compatibility.
The behavior of XLIO_SELECT_POLL_OS_FORCE can be replicated by setting:
- XLIO_SELECT_POLL_OS_RATIO=1
- XLIO_SELECT_SKIP_OS=1
Deprecate XLIO_SELECT_POLL_OS_FORCE configuration parameter and its related functionality.
- The XLIO_SELECT_POLL_OS_FORCE parameter should be marked as deprecated in the README and will be removed from future libxlio releases
- The same behavior can be achieved using XLIO_SELECT_POLL_OS_RATIO and XLIO_SELECT_SKIP_OS parameters
- This aligns with the libvma to remove this configuration while …
> issue: 4262473 Deprecate XLIO_SELECT_POLL_OS_FORCE

- src/core/dev/net_device_table_mgr.cpp
- src/core/dev/net_device_table_mgr.h
- src/core/main.cpp
In free_libxlio_resources(), we try to print report for g_p_net_device_table_mgr, however, it can be NULL if XLIO initialization fails. Check the pointer to avoid NULL pointer dereference.
Segfault fix.
Segfault fix.
> issue: 4457054 Fix segfault at exit if initialization fails

- src/core/lwip/tcp_in.c
When processing SYN+ACK in SYN_SENT state, the unacked queue is cleared but last_unacked is not updated, leaving inconsistent PCB state.
Ensure both pointers are kept in sync to maintain correct state.
> Fix PCB last_unacked in SYN_SENT state

- configure.ac
- src/core/Makefile.am
Move the auto-generation of xlio_config_schema.h from the build stage (Makefile.am) to the configure stage (configure.ac). This change provides several benefits:
- The generated header is available immediately after configure runs
- The header file is included in source distributions via EXTRA_DIST
- Separates code generation from compilation, following best practices
- Eliminates the need for BUILT_SOURCES and associated cleanup rules
The generation logic converts the JSON schema file into a C header containing a byte array representation of the schema, which is used by the configuration system at runtime.
Remove the corresponding build-time generation rules from src/core/Makefile.am and add the generated header to EXTRA_DIST. This ensures it's included in distribution tarballs.
Solves …
> issue: 4490689 move schema generation to configure

- contrib/jenkins_tests/gtest.sh
- src/core/dev/buffer_pool.cpp
- src/core/dev/ib_ctx_handler_collection.cpp
- src/core/dev/ring.h
- src/core/event/poll_group.cpp
- src/core/sock/sock-extra.cpp
- src/core/sock/sockinfo.h
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/xlio.h
- src/core/xlio_extra.h
- src/core/xlio_types.h
- src/utils/lock_wrapper.h
- tests/extra_api/xlio_ultra_api.c
- tests/extra_api/xlio_ultra_api_migrate.c
- tests/extra_api/xlio_ultra_api_server.c
- tests/gtest/Makefile.am
- tests/gtest/core/xlio_base.h
- tests/gtest/xlio_ultra_api/xlio_socket.cc
- tests/gtest/xlio_ultra_api/xlio_socket_listen_connect.cc
- tests/gtest/xlio_ultra_api/xlio_socket_migrate.cc
- tests/gtest/xlio_ultra_api/xlio_socket_migrate_2.cc
- tests/gtest/xlio_ultra_api/xlio_socket_send_receive.cc
- tests/gtest/xlio_ultra_api/xlio_socket_send_receive_2.cc
Minor improvements and fixes for the XLIO Ultra API.
Consistent doxygen documentation
Minor improvements, fixes, documentation updates
Fixes and quality improvements
> issue: 4367367 Improvements to the XLIO Ultra API

- src/core/sock/sockinfo_ulp.cpp
TLS RX offload depends on openssl library for SW encryption in case of a resync flow. Unless application is linked against openssl, XLIO cannot provide TLS RX offload support. Therefore, it's crucial to understand the environment XLIO works with if debug logs are provided offline.
Add openssl version to the debug logs.
Improve debuggability.
> issue: 4446408 Add openssl version to the debug logs

- src/core/Makefile.am
- src/core/dev/rfs.cpp
- src/core/dev/rfs.h
- src/core/dev/rfs_mc.h
- src/core/dev/rfs_uc.cpp
- src/core/dev/rfs_uc.h
- src/core/dev/rfs_uc_tcp_gro.cpp
- src/core/dev/rfs_uc_tcp_gro.h
- src/core/dev/ring_slave.cpp
- src/core/event/entity_context.cpp
- src/core/event/entity_context.h
- src/core/event/entity_context_manager.cpp
- src/core/event/entity_context_manager.h
- src/core/sock/sock-redirect.cpp
- src/core/sock/sockinfo_tcp.cpp
- src/core/sock/sockinfo_tcp.h
- src/core/sock/sockinfo_tcp_listen_context.cpp
- src/core/sock/sockinfo_tcp_listen_context.h
- src/core/util/xlio_stats.h
- src/stats/stats_reader.cpp
issue: 4315534 Add TCP listen socket/accept() support for Threads mode
Supporting TCP listen socket/accept() in Threads mode.
Socket Listen procedure is split into two phases:
** Phase1 - Called from the application context **
- prepareListen()
-- Validates socket state.
-- Auto-bind if the socket wasn't bound.
-- Transport decision (XLIO offload or OS fallback).
- Listen()
-- Backlog calculation.
-- Create listen socket clone object for every entity context.
-- Call entity context manager to distribute clones via JOB_TYPE_SOCK_ADD_AND_LISTEN.
-- Wait for listen clones to become ready.
** Phase2 - Called from Worker Thread execution context via entity_context **
- listen_socket_job()
-- Set the entity_context of the clone listen socket.
-- Update the allocation logics.
-- Add the socket …
> Thread skeleton listen Socket

- .ci/matrix_job.yaml
- .ci/pipeline/release_matrix_job.yaml
The current default JNLP image used is the one from jenkins itself, which does not support retries, this causes issues on connectivity issues to the kubernetes cloud
Add jnlpImage definition to the matrix files - Image is multi arch
[HPCINFRA-3805](https://jirasw.nvidia.com/browse/HPCINFRA-3805)
[HPCINFRA-3502](https://jirasw.nvidia.com/browse/HPCINFRA-3502)
> [CI] Issue: HPCINFRA-3502 Change default JNLP image

- .ci/opensource_jjb.yaml
Current depth sometime is not sufficient
Increase depth to 100  
It limits clone depth to some value thus speeding up the process  
The number is big enough for any reasonable action
Issue: HPCINFRA-3561
> [CI] issue: HPCINFRA-3561  Change git pull policy in CI job

- src/core/sock/sock-extra.cpp
- src/core/xlio.h
Some operations in XLIO can disable socket offload and enable "passthrough" mode. With POSIX API, this socket is passed to kernel with subsequent operations. However, XLIO Ultra API doesn't have an option to handle sockets with kernel. Therefore, we have to fail such operations if we cannot continue offloading the socket with XLIO.
This commit handles xlio_socket_bind() and xlio_socket_connect() calls.
Fail XLIO Ultra API bind() and connect() operations if socket cannot be offloaded by XLIO.
"Passthrough" sockets cannot work with XLIO Ultra API.
> issue: 4367367 Handle socket passthrough in XLIO Ultra API

- src/core/dev/net_device_val.cpp
- src/core/dev/ring.h
CQ moderation is implemented as a global timer running in the internal thread. Access to Ultra API rings must be serialized by user with the concept of polling groups. Access from the internal thread can introduce a race.
Skip such rings during CQ moderation logic. Once Ultra API interrupt mode is implemented, CQ moderation will be done per group.
Skip Ultra API rings in CQ moderation logic.
Avoid potential race.
> issue: 4610737 Skip Ultra API rings in CQ moderation

- src/core/config/descriptor_providers/xlio_config_schema.json
Extend JSON schema validation to accept both integer and string formats for memory-related buffer size parameters.
This allows users to specify sizes using human-readable units (K, M, G) in addition to raw byte values.
Changes include:
- TCP wmem: support "1MB" format alongside 1048576 bytes
- TSO max_size: support "256KB" format alongside 262144 bytes
- TX buf_size: support "0B" format alongside 0 bytes
- RX buf_size: support "0B" format alongside 0 bytes
All string formats use pattern "^[0-9]+[KMGkmg]?[B]?$" for validation and include x-memory-size metadata for proper handling.
This improves usability by allowing intuitive size specifications while maintaining backward compatibility with existing integer values.
add human-readable memory size support to buffer configurations
Fixes …
> issue: 4633383 add x-memory-size to buf config

- src/core/config/descriptor_providers/xlio_config_schema.json
Add "minimum": 0 constraint to the byte_threshold field in the TCP nodelay configuration schema.
This ensures that negative values cannot be set for the data threshold, which should be a non-negative byte count.
The byte_threshold field controls when TCP nodelay is triggered based on unsent data size, and negative values would be invalid for this purpose.
Add "minimum": 0 constraint to byte_threshold field in TCP nodelay configuration schema to prevent negative values.
Fixes 4550864.
> issue: 4550864 add minimum for nodelay_threshold

- src/core/util/sys_vars.cpp
The set_value_from_registry_if_exists() function was causing a bad any_cast error when loading the hardware_features.striding_rq.enable configuration value.
This occurred because the generic template function couldn't properly handle the boolean to enum conversion.
Replace the generic set_value_from_registry_if_exists() call with explicit type-safe operations using registry.get_value<bool>() and converting the boolean result to option_3::ON/OFF enum values.
This fixes configuration loading failures when setting: XLIO_USE_NEW_CONFIG=1 \
XLIO_INLINE_CONFIG="hardware_features.striding_rq.enable=false"
Replace set_value_from_registry_if_exists() with explicit registry.get_value<bool>() and boolean-to-enum conversion to fix bad any_cast error for hardware_features.striding_rq.enable.
fixes …
> issue: 4555854 fix bad any_cast error - striding_rq

- src/core/util/sys_vars.cpp
The set_value_from_registry_if_exists() function was causing a bad any_cast error when loading the core.exception_handling.mode configuration value.
This occurred because the generic template function couldn't properly handle the int64_t to enum conversion.
Replace the generic set_value_from_registry_if_exists() call with explicit type-safe operations using registry.get_value<int64_t>() and converting the int64_t result to xlio_exception_handling::mode values.
This fixes configuration loading failures when setting: XLIO_USE_NEW_CONFIG=1 \
XLIO_INLINE_CONFIG="core.exception_handling.mode=-2"
Replace set_value_from_registry_if_exists() with explicit registry.get_value<int64_t>() and static_cast to fix bad any_cast error for core.exception_handling.mode.
fixes 4551255.
_It is optional but …
> issue: 4551255 fix any_cast error - exception mode

- src/core/main.cpp
When configuration parameters are set to 0 (disabled), the current display only shows "Disabled" without indicating the actual value. This creates ambiguity about whether the user intentionally set the value to 0 or if there was an error.
This change modifies the display format to show both the original value and the "(Disabled)" description for better clarity. The affected parameters:
- performance.polling.iomux.poll_os_ratio
- performance.polling.iomux.skip_os
- performance.polling.rx_kernel_fd_attention_level
- performance.completion_queue.periodic_drain_msec
This provides users with clear confirmation that they intentionally set the value to 0 and that "Disabled" is the intended behavior.
Improve display clarity for disabled configuration parameters
Fixes 4551257.
_It is optional but …
> issue: 4551257 improve display clarity

- src/core/event/poll_group.cpp
Call prepare_to_close before clear_socket, as prepare_to_close expects g_p_fd_collection to be cleared only after it.
> issue: 4642277 Reorder socket cleanup in poll_group::close_socket

- src/core/config/loaders/json_loader.cpp
- tests/unit_tests/config/json_loader.cpp
This change enforces a single conf format by rejecting JSON keys that contain dots, preventing ambiguous configurations where both flat dot notation and nested object structures could be used.
Changes:
- Add validation in json_loader::process_json_object() to throw xlio_exception when keys contain dots
- Convert key to std::string for proper validation
- Add comprehensive unit tests covering:
* Method A rejection (flat dot notation like "resources.memory_limit")
* Method B acceptance (proper nested objects)
* Edge cases (multiple dots, leading/trailing dots, dots-only keys)
* Valid keys without dots still work correctly
This resolves the issue where both configuration methods were accepted:
- Method A: "core": {"resources.memory_limit": "50GB"}  (now rejected)
- Method B: "core": …
> issue: 4545376 reject JSON keys containing dots

- src/core/util/sys_vars.cpp
The current implementation only checks if the environment variable is set, but doesn't validate its value.
This can lead to incorrect behavior when the variable is set to an empty string or any non-"1" value.
Change the condition to explicitly check both:
1. If the variable is not set (NULL)
2. If the variable is set but not equal to "1"
This ensures the legacy configuration path is only used when the new config is explicitly disabled or not set.
Fix XLIO_USE_NEW_CONFIG environment variable validation to check both existence and value ("1") instead of just existence.
Fixes 4555151.
> issue: 4555151 fix XLIO_USE_NEW_CONFIG env check

- src/core/config/descriptor_providers/xlio_config_schema.json
Remove the "all" string and the integer value 6 from the list of allowed values for the "spec" profile in the configuration schema.
all was never an option for profile - remove it.
Fixes 4578714.
> issue: 4578714 Remove "all" and 6 from profiles

- src/core/config/descriptor_providers/json_descriptor_provider.cpp
- src/core/config/descriptor_providers/json_descriptor_provider.h
- src/core/config/descriptor_providers/schema_analyzer.cpp
- src/core/config/descriptor_providers/schema_analyzer.h
- src/core/config/descriptors/parameter_descriptor.cpp
- src/core/config/descriptors/parameter_descriptor.h
- tests/unit_tests/config/schema_analyzer.cpp
Fix Coverity uninitialized use warnings by explicit member init
- Add explicit default initialization for std::experimental::any members
- Add explicit empty initialization for std::vector members
- Remove Coverity suppression comments that are no longer needed
This addresses static analysis warnings about potentially uninitialized struct members by making initialization explicit rather than relying on default constructors.
Fix Coverity uninitialized use warnings by explicit member initialization
Fixes 4625345.
> issue: 4625345 Fix Coverity uninitialized use
