Mellanox/libxlio

src/core/dev/src_addr_selector.cpp

Choose ipv4 source ip according to subnet, instead of taking the first IP thats configured on the interface.

issue: 3575217 Choose ipv4 source ip according to subnet

---

.ci/create_pkg.sh
.ci/set_env.sh
.ci/template_xlio.yaml

Addin support for automatically creations
of DEB files
Adding scripts to build deb files
_Subject: Build DEB files and publish them to NFS._ 
_Justification for the PR. Task #3480683._

[CI] Adding support for build packages

---

.ci/create_pkg.sh
.ci/set_env.sh
.ci/template_xlio.yaml

Please see all comments inside https://github.com/Mellanox/libxlio/pull/13
PR13 was removed from vNext due to merge-commit.
This PR replaces PR13 with rebase-and-merge method.

[CI] Adding support for build packages (PR13 replacement)

---

README.md
config/m4/prof.m4
docs/configuration.md
src/core/main.cpp
src/core/sock/sock-redirect.cpp
src/core/util/instrumentation.cpp
src/core/util/instrumentation.h

Add profiling capability.
Add new ability as profiling socket api passing the library.
RM:3486961

issue: 3486961 Add profiling capability

---

src/core/sock/sock-redirect.cpp

Before this fix we handled only UDP listen sockets with "reuseport" directive.
This commit allows bind of all UDP sockets.

issue: 3586466 Nginx - Allow UDP listen socket

---

src/core/Makefile.am
src/core/main.cpp
src/core/proto/flow_tuple.h
src/core/sock/bind_no_port.cpp
src/core/sock/bind_no_port.h
src/core/sock/sockinfo.cpp
src/core/sock/sockinfo.h
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/util/sock_addr.h

Support IP_BIND_ADDRESS_NO_PORT using global DB for used ports.

issue: 3209984 Support IP_BIND_ADDRESS_NO_PORT

---

src/core/sock/sockinfo.cpp

Fix releasing ring flow
Suppress noise output.
RM#3604029

issue: 3604029 Fix releasing ring flow

---

src/core/dev/allocator.cpp
src/core/dev/allocator.h
src/core/dev/buffer_pool.cpp
src/core/dev/buffer_pool.h
src/core/dev/ring_simple.cpp
src/core/main.cpp
src/core/sock/sock-app.cpp
src/core/sock/tcp_seg_pool.cpp
src/core/sock/tcp_seg_pool.h
src/core/util/sys_vars.cpp
src/core/util/sys_vars.h

Implement heap allocator.
Implement heap allocator.
More efficient hugepage alignment utilization (1 allocation vs 2 allocations). Expandable buffer pools resolve unbalance between RX and TX buffers. Deprecate/remove some parameters such as number of TX/RX/ZC bufs and segments.

issue: 3580073 Implement xlio_allocator_heap

---

src/core/dev/cq_mgr.cpp
src/core/main.cpp

Fix nginx-proxy udp scenario.
Fix fd_collection initialization in case XLIO_NGINX_UDP_POOL_SIZE usage.
RM#3611687

issue: 3611687 Fix fd_collection initialization in case XLIO_NGINX_UDP_POOL_SIZE

---

src/core/dev/ring_allocation_logic.h
src/core/sock/sockinfo.cpp

Fix corruption during ring release.
Fix XLIO_RING_MIGRATION_RATIO_RX=-1
RM:3615483

issue: 3615483 Fix corruption during ring release

---

src/core/lwip/tcp_out.c

tcp_write() has an optimization to aggregate new data with the last_unsent TCP segment. However, the feature doesn't verify seqno and assumes that the last_unsent is always the most right segment in the TCP stream.
TCP fast retransmission can break this rule and insert non sequential TCP segment into the unsent queue. In the corner case, such TCP segment becomes the last_unsent and the optimization feature can append data to this segment.
As result, the appended data becomes misplaced in the TCP stream. This issue can lead to extra retransmissions, data corruptions, or even SQ corruption. For instance, TLS offload feature is affected by type overflow in case of retransmission of the spoiled TCP segment, because it doesn't expect TCP seqno outside of a TLS record.
As solution, don't allow …

issue: 3612954 Prohibit aggregation of non sequential TCP seqno

---

README.md

Add missed BlueField-3 to README.md.
Add missed supported HW to README.md.
Keep documentation updated.

issue: 3672338 Add missed BlueField-3 to README.md

---

src/core/sock/sockinfo_tcp.cpp

Linux manual doesn't describe negative listen backlog value. FreeBSD manual describes it as maximum allowed value. Linux kernel implementation and applications follow the FreeBSD description.
XLIO treats negative backlog value as minimum and replaces it with 1. This can lead to significant impact on incoming connections establishment.
Adjust XLIO to follow Linux behavior.
Treat negative listen backlog as maximum allowed (soconnmax value)
Resolve impact on incoming connection establishment rate if the listen backlog is set to negative value.

issue: 3645103 Treat negative listen backlog as maximum allowed

---

src/core/iomux/poll_call.cpp

XLIO skips kernel poll() only for offloaded sockets with events != 0. However, poll() API allows to request offloaded socket with events = 0, because POLLERR and POLLHUP are always enabled implicitly.
In the above scenario, XLIO passes offloaded socket fd to kernel which can return POLLHUP immediately and user receives a wrong event as result.
Since POLLERR and POLLHUP are always enabled implicitly and they're already treated as READ type, assign the READ type unconditionally for each socket. This forces to check skip_os_select() even in case of events = 0.
Check skip_os_select() for offloaded sockets even if events=0.
Fix poll() functionality for sockets with events=0.

issue: 3684889 Fix poll() for offloaded sockets with events=0

---

src/core/dev/ring_bond.h
src/core/dev/ring_simple.h
src/core/iomux/epfd_info.h
src/core/sock/fd_collection.h
src/core/sock/socket_fd_api.h
src/core/sock/sockinfo.h
src/core/sock/sockinfo_nvme.h
src/core/sock/sockinfo_tcp.h
src/core/sock/sockinfo_udp.h

3695190 Separate data and method members in sockinfo* classes

issue: 3695190 Separate data and method members

---

contrib/jenkins_tests/gtest.sh
src/core/proto/xlio_lwip.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/util/sysctl_reader.h
src/core/util/utils.cpp
tests/gtest/tcp/tcp_sockopt.cc

Bring some of the changes made in LibVma

Issue 3664594 keepalive backport

---

src/core/lwip/tcp_out.c

This change will allow to piggyback the ACK when a TCP segment split is anticiapted due to small tx congestion window.
We will not send empty ack, and instead split the next unsent segment to fit into the congestion window, and piggyback the ACK we need to send.
We hit a deadlock before this change where application sent data and didn't get completions by XLIO because the congestion window was still small (start of the world), and we didn't send any data on received ack by the remote side.
Instead - we should send any data we got on unsent queue once we get any ACK by remote side.

issue: 3574064 Allow tx segment split on ACK recv

---

src/core/sock/sockinfo.cpp
src/core/sock/sockinfo.h
src/core/sock/sockinfo_tcp.cpp
tests/gtest/common/sys.cc
tests/gtest/extra_api/extra_poll.cc
tests/gtest/tcp/tcp_sockopt.cc

Complete socket isolation feature with TCP incoming sockets inheritance. Add gtests for CI.
TCP incoming sockets support and gtests.
Complete socket isolation feature.

issue: 3698256 Socket isolation feature: TCP incoming and gtests

---

contrib/jenkins_tests/rpm.sh

Issue: HPCINFRA-919
Add private email scan in deb/rpm packages
Make sure we dont have any private emails in rom/deb packages information or changelog 
RM3375239

Issue: 3375239 - add email scan in packages

---

src/core/dev/buffer_pool.h
src/core/dev/ring.h
src/core/dev/ring_bond.h
src/core/dev/ring_simple.cpp
src/core/dev/ring_simple.h
src/core/dev/ring_tap.h
src/core/lwip/pbuf.c
src/core/lwip/pbuf.h
src/core/lwip/tcp.c
src/core/lwip/tcp.h
src/core/lwip/tcp_impl.h
src/core/lwip/tcp_in.c
src/core/lwip/tcp_out.c
src/core/proto/dst_entry_tcp.cpp
src/core/sock/sock-redirect.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/sock/sockinfo_ulp.cpp
src/core/xlio_extra.h

Productize an improved data path from express PoC
What
Get the LwiP-related changes
Why?
Reduce networking latency and CPU cache coherency.

Issue 3668182 productize lwip express data path

---

contrib/jenkins_tests/build.sh
src/core/libxlio.c
src/core/main.cpp
src/core/sock/sock-redirect.cpp
src/core/sock/sock-redirect.h
src/core/util/agent.cpp
src/core/xlio.h

issue: 3724170 Add missing ifdef __cplusplus

---

src/core/sock/sock-redirect.h

Issue 3771283 fix function pointers

---

CHANGES
configure.ac
contrib/scripts/libxlio.spec.in

Version 3.30.1

---

src/core/dev/buffer_pool.cpp
src/core/dev/cq_mgr_rx_strq.cpp
src/core/sock/sockinfo_tcp.cpp

Add `if (likely(ptr)...)` to fix compilation errors/warnings.

Issue 3808935 fix lto errors

---

CHANGES
configure.ac
contrib/scripts/libxlio.spec.in

version: 3.30.3

---

src/core/sock/sockinfo_tcp.cpp

In heavy CPS scenarios a socket may go to TIME-WAIT state and be reused before first TCP timer registration is performed by internal-thread.
1. Setting timer_registered=true while posting the event prevents the second attemp to try and post the event again.
2. Adding sanity check in add_new_timer that verifies that the socket is not already in the timer map. 

issue: 3855390 Fixing adding TCP timer twice warning

---

contrib/jenkins_tests/vg.sh

Update valgrind verification.
Align valgrind parameters with library requirements
Make valgrind workable

issue: 3556418 Update valgrind verification

---

contrib/jenkins_tests/cov.sh

We're requested to upgrade the Coverity version to 2023.12
The PR runs Coverity v2023.12 against the Xlio codebase

issue: HPCINFRA-1734 [CI] Coverity: upgrade to v2023.12

---

src/core/iomux/epoll_wait_call.cpp
src/core/sock/fd_collection.cpp
src/core/sock/fd_collection.h
src/core/sock/sockinfo.h
src/core/sock/sockinfo_nvme.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/sock/sockinfo_ulp.cpp
src/core/util/xlio_list.h
src/vlogger/vlogger.cpp
src/vlogger/vlogger.h

Scattered improvements cherry-picked from #109.
Scattered improvements cherry-picked from #109.
Performance / code quality improvements.

issue: 3788369 Improvements from XLIO Socket / Storage API activity

---

src/core/sock/sockinfo_tcp.cpp

rx_lwip_cb_xlio_socket() missed RX statistics and xlio_stats showed zeros as result. Save the stats.
Fix RX stats for XLIO Socket API.
Fix RX stats for XLIO Socket API.

issue: 3947690 Fix RX statistics for XLIO Socket API

---

CHANGES
configure.ac
contrib/scripts/libxlio.spec.in

version: 3.31.1

---

config/m4/doca.m4
configure.ac
src/core/Makefile.am
src/core/dev/allocator.cpp
src/core/dev/hw_queue_rx.cpp
src/core/dev/hw_queue_rx.h
src/core/dev/hw_queue_tx.cpp
src/core/dev/ib_ctx_handler.cpp
src/core/dev/ib_ctx_handler.h
src/core/dev/ib_ctx_handler_collection.cpp
src/core/dev/net_device_val.cpp
src/core/main.cpp
src/core/sock/sockinfo.cpp
src/core/util/sys_vars.cpp
src/vlogger/vlogger.h

1. Initial linkage with DOCA
2. Opening DOCA device
3. Opening ETH RXQ
This is the initial changes that enable XLIO to compile and run with DOCA performing basic operation.

issue: 3623390 Initial DOCA linkage and basic operations

---

src/core/dev/ib_ctx_handler_collection.cpp

Print DOCA error as XLIO debug info instead of XLIO error
Print DOCA error as XLIO debug info instead of XLIO error

issue: 3976050 Change error print to debug print

---

src/core/dev/ib_ctx_handler_collection.cpp
src/vlogger/vlogger.h

In container environment DOCA finds some ib devices with no related interface
In container environment DOCA finds some ib devices with no related interface

issue: 3976049 Changing unfound device error message to warning

---

contrib/jenkins_tests/copyright-check-map.yaml
tests/nginx/constant_reply_module/README.md
tests/nginx/constant_reply_module/config
tests/nginx/constant_reply_module/ngx_http_constant_reply_module.cpp

Adding Nginx Constant Reply Module.
This module allows to send simple constant replies from Nginx without accessing files or system resources. See module README for more information.
Nginx performance benchmarking

issue: 3807308 [Test] Nginx constant reply module

---

src/core/lwip/tcp.h
src/core/sock/sockinfo_tcp.cpp

Non-zerocopy (XLIO_SOCKET_SEND_FLAG_INLINE) operations reuse common tcp_write() which doesn't allow the queue to grow beyond specific number of pbufs. The limit is derived from the TCP send buffer and usually equals to hundreds or thousands of pbufs.
XLIO Socket API encourages users to limit the inflight data and allows send operations to fails with the unrecoverable ENOMEM error. However, on the other hand, the API describes that send operations aren't limited by send buffer logic.
To follow current XLIO Socket API description, allow the TCP queue to grow. To do this, increase the queue limit to 16M pbufs for XLIO sockets.
Allow XLIO socket queue to grow for non-zc sends.
Better follow XLIO Socket API description and avoid unrecoverable ENOMEM errors in case of long queues.
What kind of …

issue: 3992651 Allow XLIO socket queue to grow for non-zc sends

---

src/core/iomux/epfd_info.cpp
src/core/iomux/epfd_info.h
src/core/iomux/epoll_wait_call.cpp
src/core/iomux/epoll_wait_call.h
src/core/iomux/io_mux_call.cpp
src/core/iomux/io_mux_call.h
src/core/sock/fd_collection.h
src/core/util/sys_vars.cpp

Fixing Performance with epoll use cases. 
See commit message. 
Performance fix.

issue: 3502635 Avoid epoll OS polling through internal thread

---

.ci/pipeline/release_jjb.yaml
.ci/pipeline/release_matrix_job_dr.yaml

Support for release process in DRP is required, since the envrironment is different than the prod environment there should be a new pipeline defined with said changes
Add new job template definition to release_jjb
Add new dr matrix with configuration for PDC env
Issue: HPCINFRA-776

Issue: HPCINFRA-776 Disaster recovery pipeline

---

src/core/dev/cq_mgr_tx.cpp
src/core/dev/hw_queue_tx.cpp
src/core/dev/hw_queue_tx.h
src/core/dev/ring.h
src/core/dev/ring_bond.h
src/core/dev/ring_simple.cpp
src/core/dev/ring_simple.h
src/core/dev/ring_tap.h
src/core/main.cpp
src/core/proto/dst_entry_tcp.cpp
src/core/proto/dst_entry_tcp.h
src/core/proto/neighbour.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/util/cached_obj_pool.h
src/core/util/sys_vars.cpp
src/core/util/sys_vars.h
src/core/util/xlio_stats.h
src/stats/stats_reader.cpp

[0001-Disable-suspend-during-epoll.patch](https://github.com/user-attachments/files/16740209/0001-Disable-suspend-during-epoll.patch)
Used by XLIO_DOCA_TX=1.
Based on:
https://github.com/AlexanderGrissik/libxlio/commits/doca_rx/
Addresses both tasks:
https://redmine.mellanox.com/issues/3898049
https://redmine.mellanox.com/issues/3898052

issue: 3898049 DOCA Tx data path implementation

---

.ci/dockerfiles/Dockerfile.ubuntu22.04
config/m4/doca.m4
contrib/jenkins_tests/globals.sh

Update DOCA min required version to 2.9.0029
Enable new DOCA features

issue: 3898109 Bump to DOCA version 2.9.0029

---

src/core/dev/hw_queue_rx.cpp
src/core/dev/hw_queue_rx.h

RX task batching
See commit message

issue: 3898109 DOCA RX Task batching

---

.ci/matrix_job.yaml
.ci/opensource_jjb.yaml
.ci/pipeline/release_jjb.yaml
.ci/pipeline/release_matrix_job.yaml
.ci/pipeline/release_matrix_job_dr.yaml

We update references to Jenkins's secrets
We update CI with updated Jenkins secrets references
Secrets Scanner does not work correctly with the old secrets format

HPCINFRA-2572 secrets scanner

---

contrib/jenkins_tests/globals.sh
contrib/jenkins_tests/style.sh
contrib/jenkins_tests/test.sh
contrib/jenkins_tests/vg.sh
src/core/dev/hw_queue_rx.cpp
src/core/dev/hw_queue_tx.cpp
src/core/dev/hw_queue_tx.h
src/core/dev/net_device_val.cpp
src/core/dev/rfs_rule.cpp
src/core/dev/rfs_rule.h
src/core/dev/ring.h
src/core/dev/ring_bond.cpp
src/core/dev/ring_bond.h
src/core/dev/ring_simple.cpp
src/core/dev/ring_simple.h
src/core/dev/ring_tap.cpp
src/core/dev/ring_tap.h
src/core/iomux/epfd_info.cpp
src/core/main.cpp
src/core/proto/dst_entry_tcp.cpp
src/core/proto/dst_entry_tcp.h
src/core/sock/sockinfo.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/util/sys_vars.cpp
src/core/util/sys_vars.h
tests/python_tests/rfs/tcp_client.py
tests/python_tests/rfs/tcp_server.py

DOCA fixes and gaps integrations.
1. Make DOCA the default data path
2. Fixing Notification channel handling and registration
3. Gap - Fixing LSO buffer chaining
4. Gap - Adding Flow Tag 
5. Gap - Adding MSS per LSO task

issue: 4082814 Integrating DOCA gaps mss, flow-tag and chaining

---

src/core/sock/sockinfo_tcp.cpp

1. Fix rx_wait_helper
2. Improve XLIO_SKIP_POLL_IN_RX flag.
See commit message 
Nginx performance and functionality

issue: 4082058 Fixing return from rx_wait_helper without data

---

.ci/dockerfiles/Dockerfile.openeuler22.03-sp1
.ci/matrix_job.yaml
.ci/opensource_jjb.yaml
.ci/scripts/doca_install.sh

Add new OS support to CI
Ctyunos 23.01
As per request: HPCINFRA-2686

issue: HPCINFRA-2686: Add new OS support to CI: Ctyunos 23.01

---

src/core/dev/buffer_pool.cpp

Add null check to prevent pointer dereference

issue: 4154286 Fix print report logic

---

.ci/dockerfiles/Dockerfile.ubuntu22.04
config/m4/doca.m4
contrib/jenkins_tests/globals.sh
src/core/dev/hw_queue_rx.cpp
src/core/dev/hw_queue_tx.cpp
src/core/dev/ib_ctx_handler.cpp
src/core/dev/ib_ctx_handler.h
src/core/dev/net_device_val.cpp
src/core/dev/rfs_rule.cpp
src/core/iomux/epfd_info.cpp

1. Bump DOCA version to 2.10.0025
2. Integrate new notification mechanism
New notification mechanism does not require DOCA patches anymore
Integrate new features

issue: 4144194 Integrating progress-all notification mechanism

---

src/core/dev/cq_mgr_tx.cpp
src/core/dev/cq_mgr_tx.h
src/core/dev/hw_queue_tx.cpp
src/core/dev/hw_queue_tx.h
src/core/dev/net_device_val.cpp
src/core/dev/ring.h
src/core/dev/ring_bond.cpp
src/core/dev/ring_bond.h
src/core/dev/ring_simple.cpp
src/core/dev/ring_simple.h
src/core/iomux/epfd_info.cpp

1. Optimize return TX buffer to global pool handling
2. Simplify TX poll_and_process_tx return value

issue: 4159516 Optimize return to global pool for DOCA path

---

contrib/jenkins_tests/vg.sh

issue: 4235300 valgrind with doca

---

.ci/dockerfiles/Dockerfile.ubuntu22.04
config/m4/doca.m4
contrib/jenkins_tests/globals.sh

Update min required DOCA version
Require version 2.10.0045
Resolved issues in DOCA.

issue: 4144194 Bumping DOCA version to 2.10.0045

---

.ci/pipeline/xlio_doca_ci_jjb.yaml

Move to media team dedicated service user
Shared user sometimes been abused by other teams causing GitHub token exhaustion
This causes delays in GHPRB plug in response
Issue: HPCINFRA-3444

[CI] Update GHPRB service user on doca_xlio_vNext branch

---

src/core/proto/dst_entry_tcp.cpp

In the past, XLIO held a linked list of buffers posted to the SQ. For a multi-buffer packets, only the head buffer was accounted. Since a TCP retransmission would lead to duplicate insertion to the list and a list corruption as result, a workaround was introduced with a fake buffer for accounting.
The approach with the buffers list was reworked and the workaround is not needed anymore.
Remove a non-needed workaround in dst_entry_tcp::fast_send().
Code cleanup and improve code robustness.

issue: 4432892 Remove leftover workaround in dst_entry_tcp::fast_send()

---

.ci/do_release.sh

do_release fails in line 72 due to missing space between the caluse and the brackets
Fix do_release

[CI] issue: 4377705 Bugfix missing space in if clause

---

.ci/blackduck_source.sh
.ci/do_release.sh
.ci/dockerfiles/Dockerfile.rhel8.6
.ci/matrix_job.yaml
.ci/opensource_jjb.yaml
contrib/build_pkg.sh

Release 3 51 ci

---

src/core/util/list.h
tests/gtest/mix/mix_list.cc

Replace linux list with BSD list due to license

issue: 4432537  Replace linux list with BSD list

---

README
src/core/config/descriptor_providers/xlio_config_schema.json
src/core/config/mappings.py
src/core/dev/ring_allocation_logic.cpp
src/core/event/delta_timer.cpp
src/core/event/delta_timer.h
src/core/event/event_handler_manager.cpp
src/core/event/event_handler_manager.h
src/core/main.cpp
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/util/sys_vars.cpp
src/core/util/sys_vars.h
src/core/util/sysctl_reader.h

FR 3886011
Removing TCP control packets handling on internal thread.
Quality

issue: 3886011 Removing TCP control thread mode

---

src/core/sock/sockinfo_tcp.cpp

Fix for issues:
4503518
4502938
See commit message.
Bug fix

issue: 4502938 Fixing TLS RX ZC buffer tcp_tx_pbuf_alloc

---

src/core/config/generate_mappings.py
src/core/config/mappings.py

The `generate_mappings.py` script, which processes the JSON schema to create environment variable mappings, was incorrectly interpreting the `additionalProperties` schema keyword as a configurable property. This could lead to invalid entries in the generated `mappings.py`.
This patch corrects the script to ignore `additionalProperties` during schema processing, ensuring only actual configuration properties are mapped.
Additionally, the `extra_api` section has been removed from the configuration schema, but its mappings remained in `mappings.py`. These stale entries have been removed to align with the current schema.
This pull request addresses two issues within the configuration management system. First, it corrects a bug in the `generate_mappings.py` script that improperly processed the …

issue: 4490408 update mapping generation

---

src/stats/stats_reader.cpp

In the condition, Take into consideration all the counters involved in the printf statment.

issue: Fix HW tls counters

---

.ci/dockerfiles/Dockerfile.ctyunos23.01
.ci/matrix_job.yaml

fix ctyuneos repository reachability issues
Original repos suffer from sporadic connectivity issues
Replaced the original repo URLs with webrepo ones

[CI] issue: HPCINFRA-3796 fix ctyuneos repository reachability issues

---

SECURITY.md

Add SECURITY.md
Following SCM security hardening requirements public repos must contain security policies

[CI] issue HPCINFRA-3392 Add SECURITY.md

---

src/core/event/entity_context.cpp
src/core/event/entity_context.h
src/core/proto/dst_entry.cpp
src/core/proto/dst_entry.h
src/core/sock/sockinfo.h
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/sock/sockinfo_udp.h

This is a split 'connect' commit from approved PR https://github.com/Mellanox/libxlio/pull/390

issue: 4315534 Adding connect() support for Threads mode

---

contrib/jenkins_tests/test.sh

We need to collect existing logs generated by `verifier.pl` even if it fails. Log collection executed by `do_archive` function but the script exits before it due to configured '-e' option
Temporary set '+e' option around `verifier.pl` to allow further code execution and catch an error if exists. `do_archive` will handle log  collection

[CI] Fix log collection

---

src/core/config/descriptor_providers/json_descriptor_provider.cpp
src/core/dev/rfs_uc.cpp
src/core/event/entity_context.cpp
src/core/event/entity_context.h
src/core/event/entity_context_manager.cpp
src/core/iomux/epfd_info.cpp
src/core/iomux/epfd_info.h
src/core/iomux/epoll_wait_call.cpp
src/core/iomux/io_mux_call.cpp
src/core/sock/sockinfo.cpp
src/core/sock/sockinfo.h
src/core/sock/sockinfo_tcp.cpp
src/core/sock/sockinfo_tcp.h
src/core/util/xlio_list.h

Adding epoll support for threads mode.
See commit messages for more info.
Multithreaded optimization

issue: 4315534 Adding threads mode epoll support

---

src/core/sock/sockinfo_tcp.cpp

Add support to SO_BINDTODEVICE in worker threads mode

issue: 4315534 Add support to SO_BINDTODEVICE in worker threads mode

---

src/core/proto/dst_entry.cpp

Fixing crash in case of unresolved neigh in threads mode connect
See commit message
XLIO threads mode

issue: 4315534 Fix unresolved neigh crash in threads mode

---

src/core/iomux/epfd_info.cpp
src/core/iomux/epfd_info.h
src/core/sock/sockinfo_tcp.cpp

XLIO dual port enhancement

---

src/core/xlio.h

Minor changes to the documentation.
Minor changes to the documentation.
Documentation improvement.

issue: 4367367 Polish Ultra API documentation

---

contrib/jenkins_tests/style.sh
examples/README.md
examples/xlio_ultra_api_ping_pong.c

examples/xlio_ultra_api_ping_pong.c is a simple example of a client-server application as a starting point to get familiar with the API.
Also, add clang-format coverage for new examples/ directory.
Add XLIO Ultra API example.
Improve user experience.

issue: 4649710 Add XLIO Ultra API example application
